baseURL = "https://transcendent-cocada-58da96.netlify.app//"
# baseURL = "https://mdpwebdevelopment.com/"
# baseURL = "https://shaunagra-custom-frames.ie/hugo-test/"
title = "Personalised Frames Ireland | Gift Frames & Cards"
theme = "hugo-universal-theme"

languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "shauna-gra"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-121714901-1"


# Define the number of posts per page
paginate = 30

[menu]

# Main menu


[[menu.main]]
    identifier = "frames"
    name = "Frames"
    url  = "/frames/"
    weight = 2

    [[menu.main]]
    identifier = "cards"
    name = "Cards"
    url  = "/cards/"
    weight = 3

[[menu.main]]
    identifier = "sale-news"
    name = "Sale News"
    url  = "/sale-news/"
    weight = 4


    [[menu.main]]
    identifier = "reviews"
    name = "Reviews"
    url  = "/reviews/"
    weight = 5

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 6

[[menu.main]]
    identifier="about"
    name = "About"
    url  = "/about/"
    weight = 7

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 8

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 9



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/ShaunaGra17"
    pre = "<i class='fab fa-2x fa-facebook'></i>"



[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "shaunagra17@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Shauna Gra"
    defaultKeywords = ["personalised frames", "personalised cards"]
    mainSections = ["blog"]
    defaultDescription = "Personalised Frames Ireland, Personalised Creative Gift Frames & Cards, Frames With Names And Dates, Dublin Ireland, Worldwide Shipping."

    # Social media
    facebook_site = "https://www.facebook.com/ShaunaGra17" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    # twitter_site = "" # the Twitter handle of your site (without the '@')
    # default_sharing_image = "img/logo.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, greenSpringGlam, green, marsala, pink, red, turquoise, violet, greenSpring, lightPink
    style = "greenSpringGlam"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/xayvlkqa"
    contact_form_ajax = false

   about_us = "<p>I chose the name Shauna Gra because our beautiful daughter is called Shauna, which means Present from God in Irish, and Gra means love in Irish. So we thought combining the two fitted perfectly with what we were hoping to achieve, handcrafted gifts made with lots of love.</p>"
    copyright = "Copyright (c) 2023, Shauna Gra; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo"
    logo_small = "img/logo-small"
    address = """<p class="text-uppercase"><strong>Shauna Gra</strong>
        <br>Dublin<br>
        <strong>Ireland</strong>
      </p>
      """



[permalinks]
    blog ="/:filename/"





# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    categoriesTT = true
    categoriesResources = true

    tags = true
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "Here is what some of our happy customers had to say."

[params.see_more]
    enable = true
    icon = "fas fa-shopping-cart"
    title = "Browse our personalised frames"
    subtitle = ""
    link_url = "frames/"
    link_text = "Shop Now"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Here are some of our most recent blog posts, be sure to check them out and subscribe to our email list so that you don't miss out on any of our new posts."
    hide_summary = false

 [taxonomies]
  tag = "tags" 
  category = "categories"
 
